apiVersion: apps/v1
kind: Deployment
metadata:
  name: aqua-deployment-lb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app-lb
  template:
    metadata:
      labels:
        app: web-app-lb
    spec:
      containers:
      - name: dev-container
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-lb
  labels:
    app: web-app-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: web-app-lb
